version: '3'
services:
  redis:
    image: "redis:alpine"
    networks:
      - cache_nw
  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    networks:
      - db_nw
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
networks:
  db_nw:
    driver: bridge
  cache_nw:
    driver: bridge