db:
  datasources:
    postgres:
      uri: "host=localhost port=5432 user=postgres dbname=gouthy password=postgres sslmode=disable"
      db_type: "postgres"
      automigrate: false
    in_memory:
      uri: "file:memdb1?mode=memory&cache=shared"
      db_type: "sqlite"
      automigrate: true
  default: in_memory
  automigrate: true


server:
  port: ':5000'


jwk:
  keys: './data/jwks'

redis:
  addr: "localhost:6379"
  password: ""