db:
  datasources:
    postgres:
      uri: "host=localhost port=5432 user=postgres dbname=gouthy password=postgres sslmode=disable"
      db_type: "postgres"
      automigrate: false
    in_memory:
      uri: "file:memdb1?mode=memory&cache=shared"
      db_type: "sqlite"
      automigrate: true
      data_import:
        - "data/samples/sample-data.yml"
    sqlite:
      uri: "file:data/db/sample.db&cache=shared"
      db_type: "sqlite"
      automigrate: true
      data_import:
        - "data/samples/sample-data.yml"
  default: in_memory
  automigrate: true


server:
  port: ':5000'


jwk:
  keys: './data/jwks'

redis:
  addr: "localhost:6379"
  password: ""

features:
  password_policy:
    enabled: true
    params:
      min_length: 8
      max_length: 255
      score: 1