db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: gouthy
  sslmode: disable

server:
  port: ':5000'


jwk:
  keys: './data/jwks'

redis:
  addr: "localhost:6379"
  password: ""