DROP TRIGGER IF EXISTS SetUpdated_Clients;
DROP TRIGGER IF EXISTS SetUpdated_Secrets;
DROP TABLE IF EXISTS Accounts;
DROP TABLE IF EXISTS Secrets;
DROP TABLE IF EXISTS LastLoginAudit;
DROP TABLE IF EXISTS AccountStateAudit;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Machines;