DROP TABLE IF EXISTS Entities;
DROP TABLE IF EXISTS Secrets;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Machines;

DROP TABLE IF EXISTS AutomaticSecurityCodes;
DROP TABLE IF EXISTS EnityStateAudit;

DROP TRIGGER IF EXISTS SetUpdated_Secrets;
DROP TRIGGER IF EXISTS SetUpdated_Entities;
DROP TRIGGER IF EXISTS SetUpdated_Users;
DROP TRIGGER IF EXISTS SetUpdated_Machines;


